package world

import (
	"testing"

	"voxelcraft.ai/internal/protocol"
	"voxelcraft.ai/internal/sim/catalogs"
)

func TestBoundaryWriteConsistency_PlaceOutsideFailsAndNoInventoryLoss(t *testing.T) {
	cats, err := catalogs.Load("../../../configs")
	if err != nil {
		t.Fatalf("load catalogs: %v", err)
	}
	w, err := New(WorldConfig{ID: "test", Seed: 3, BoundaryR: 8}, cats)
	if err != nil {
		t.Fatalf("world: %v", err)
	}

	resp := make(chan JoinResponse, 1)
	w.handleJoin(JoinRequest{Name: "builder", DeltaVoxels: false, Out: nil, Resp: resp})
	jr := <-resp
	a := w.agents[jr.Welcome.AgentID]
	if a == nil {
		t.Fatalf("missing agent")
	}
	// Avoid tick-0 scripted events.
	w.tick.Store(1)

	a.Pos = Vec3i{X: 0, Y: 0, Z: 0}

	a.Inventory = map[string]int{"CRAFTING_BENCH": 1}

	outPos := Vec3i{X: w.cfg.BoundaryR + 1, Y: 0, Z: 0}
	act := protocol.ActMsg{
		Type:            protocol.TypeAct,
		ProtocolVersion: protocol.Version,
		Tick:            w.CurrentTick(),
		AgentID:         a.ID,
		Tasks:           []protocol.TaskReq{{ID: "K1", Type: "PLACE", ItemID: "CRAFTING_BENCH", BlockPos: outPos.ToArray()}},
	}
	w.step(nil, nil, []ActionEnvelope{{AgentID: a.ID, Act: act}})

	if got := a.Inventory["CRAFTING_BENCH"]; got != 1 {
		t.Fatalf("inventory changed on out-of-bounds place: got %d want 1", got)
	}

	// Verify TASK_FAIL is E_INVALID_TARGET for this request.
	taskID := ""
	for _, e := range a.Events {
		if e["type"] != "ACTION_RESULT" || e["ref"] != "K1" {
			continue
		}
		if ok, _ := e["ok"].(bool); !ok {
			t.Fatalf("expected ACTION_RESULT ok=true, got ok=%v code=%v", e["ok"], e["code"])
		}
		if s, _ := e["task_id"].(string); s != "" {
			taskID = s
		}
		break
	}
	if taskID == "" {
		t.Fatalf("missing task_id from ACTION_RESULT")
	}

	foundFail := false
	for _, e := range a.Events {
		if e["type"] != "TASK_FAIL" || e["task_id"] != taskID {
			continue
		}
		foundFail = true
		if code, _ := e["code"].(string); code != "E_INVALID_TARGET" {
			t.Fatalf("expected E_INVALID_TARGET, got %v", e["code"])
		}
		break
	}
	if !foundFail {
		t.Fatalf("expected TASK_FAIL for out-of-bounds place")
	}
}

func TestBoundaryWriteConsistency_SetBlockOutsideDoesNotGenerateChunk(t *testing.T) {
	s := NewChunkStore(WorldGen{Air: 0, BoundaryR: 8})
	if got := len(s.LoadedChunkKeys()); got != 0 {
		t.Fatalf("unexpected initial chunk keys: %d", got)
	}

	s.SetBlock(Vec3i{X: 1000, Y: 10, Z: 0}, 1)
	if got := len(s.LoadedChunkKeys()); got != 0 {
		t.Fatalf("expected no chunks to be generated by out-of-bounds SetBlock, got %d", got)
	}
}
